export const CURATION_VER = "getCurationVer"
export const CONFIG_VER = "getConfigVer"
export const CRAWLER_VER = "getCrawlerVer"
export const ENGINE_VER = "getEngineVer"
export const EMAIL_VER = "getEmailVer"
export const USER_VER = "userVer"